package analisador;

public enum Token {
	OPERADOR_ARITMETICO, OPERADOR_LOGICO, OP_RELACIONAL, OP_BOOLEANO, 
	DELIMITADOR, COMENTARIO, PALAVRA_CHAVE, ID,  LIT_INTEIRO, LIT_FLUTUANTE, ERROR, 

}
